### ISSUE TITLE
Bug: LM mentioned in a crash report

### ISSUE THREAD

**Issue by LSSwwwwwww** [lokka30/LevelledMobs#267] opened 2021-08-08 11:37 UTC
Hello, my server has crashed again.

Log file: [2021-08-08-2.log](https://github.com/lokka30/LevelledMobs/files/6950631/2021-08-08-2.log)

Do you think is caused by LevelledMobs? If not, do you know which plugin caused this? 

By the way, my Discord account was stolen around 8:00 this morning. I'm very sorry for this. I can't send you a message on Discord.

**Comment by lokka30** [comment] 2021-08-08 12:40
Hello, were you MC_w? If so we had to ban you as your account spammed advertisement links throughout the server.

Your crash report does not show enough information to prove which plugin is causing the crash. It seems a user was using menus, then teleported using `/back`, then the server crashed.

Yes, LevelledMobs has a few lines present inside the crash log. Does this mean LevelledMobs is the cause of your issue? Very unlikely. I don't know who you can contact to get this issue resolved but I would suggest you look at your timings. If you can prove LevelledMobs is the cause then please let us know.

**Comment by lokka30** [comment] 2021-08-09 12:17
I will close this issue until it is confirmed. I have a hard time believing LM is the cause of the crash.

**Closed by lokka30** 2021-08-09 12:17 UTC
Labels: bug, unconfirmed

**Comment by LSSwwwwwww** [comment] 2021-08-10 14:57
You can close it.I find the error&nbsp;origin is the aurora.Your plugin doesn't have error thanks a lot.a




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lokka30/LevelledMobs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月9日(星期一) 晚上8:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lokka30/LevelledMobs] Bug: LM mentioned in a crash report (#267)





 
I will close this issue until it is confirmed. I have a hard time believing LM is the cause of the crash.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
