### ISSUE TITLE
Request: Make all keys inside yml files case in-sensitive

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#231] opened 2021-06-21 05:08 UTC
**Is your feature request related to a problem? Please describe.**
All yml file parsing should be case in-sensitive when parsing

**Describe the solution you'd like**
MINLEVEL and mInLeVeL should work the same in rules.yml and customdrops.yml

**Describe alternatives you've considered**
None

**Additional context**

**Comment by UltimaOath** [comment] 2021-06-21 05:53
I second the motion lol had lots of issues so far related to this
particular issue.

**Comment by lokka30** [comment] 2021-07-03 10:54
@stumper66 @UltimaOath Was this fixed?

**Comment by UltimaOath** [comment] 2021-07-03 11:41
Listed as fixed in 3.1.0  b447 ; I personally have not tested not sure if
Penal has or not. If not, I can make sure it's tested out on Monday/Tuesday.

**Comment by UltimaOath** [comment] 2021-07-06 03:54
Tested in b455; Didn't test every possibility but overall the system works as intended.

**Closed** 2021-07-06 05:48 UTC
Labels: enhancement, needs testing
