### ISSUE TITLE
Could not pass CreatureSpawnEvent to LevelledMobs

### ISSUE THREAD

**Issue by Sam-Diggity** [lokka30/LevelledMobs#86] opened 2020-06-29 17:48 UTC
This error is sent to my console and is preventing the plugin from running properly: 
![image](https://user-images.githubusercontent.com/35472814/86038685-50237c00-ba0f-11ea-90d4-1f3f22c90a72.png)
I am running spigot 1.16.1 and I do have PhantomLib installed. I haven't touched the config.

**Comment by lokka30** [comment] 2020-07-02 09:09
Please ensure you are running the latest Spigot 1.16.1 jar from BuildTools. Re-run build tools, replace the old jar and try again :)

**Comment by lokka30** [comment] 2020-07-04 00:41
@Sam-Diggity ?

**Comment by Sam-Diggity** [comment] 2020-07-09 20:14
Sorry for the late reply. I reinstalled the latest version of Spigot and it is still throwing the same error.

**Comment by lokka30** [comment] 2020-07-09 23:41
> Sorry for the late reply. I reinstalled the latest version of Spigot and it is still throwing the same error.

Just to make sure - you have re-ran BuildTools?
What's happening here is that the entity for some reason doesn't have the attribute 'GENERIC_MAX_HEALTH', which almost all entities do.
I am asking if you are using the latest version of Spigot 1.16.1 as older versions of Spigot 1.16.1 had a big bug where all entities had no attributes.

**Comment by lokka30** [comment] 2020-07-09 23:47
Also, if you prefer communication over Discord or Spigot, I'm happy to do that too.

**Comment by lokka30** [comment] 2020-07-13 00:11
Issue is not seeing activity from the poster.

I am 90% sure that the issue is not having the ***LATEST*** version from BuildTools.
* Run BuildTools again for 1.16.1
* Delete your old server's jar and replace it with the one BuildTools just made
* Should be fixed.

**Closed by lokka30** 2020-07-13 00:11 UTC
Labels: bug, further info required
